# Generated by Django 5.2.11 on 2026-03-20 07:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.FloatField(blank=True, help_text='Leave blank if no discount', null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mens', "Men's Wear"), ('womens', "Women's Wear"), ('kids', "Kid's Wear"), ('bags', 'Bags'), ('purses', 'Purses'), ('belts', 'Belts'), ('sunglasses', 'Sun Glasses'), ('makeup', 'Makeup'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
