# Generated by Django 5.2.11 on 2026-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashion', '0002_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('saree', 'Sarees'), ('kurti', 'Kurtis'), ('western', 'Western'), ('traditional', 'Traditional'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
