# Generated by Django 5.2.11 on 2026-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashion', '0003_product_description_product_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
