# Generated by Django 5.2.11 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashion', '0004_vendor_shop_address_vendor_shop_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mens', "Men's Wear"), ('womens', "Women's Wear"), ('kids', "Kid's Wear"), ('bags', 'Bags'), ('purses', 'Purses'), ('belts', 'Belts'), ('sunglasses', 'Sun Glasses'), ('makeup', 'Makeup'), ('footwear', 'Footwear'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
