# Generated by Django 5.2.11 on 2026-03-28 05:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efashion', '0006_color_size_product_brand_name_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
