# Generated by Django 5.2.11 on 2026-04-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashion', '0008_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('jackets', 'Jackets'), ('tshirts', 'T-shirts'), ('shirts', 'Shirts'), ('hoodies', 'Hoodies'), ('menpants', 'Menpants'), ('traditional', 'Traditional'), ('saree', 'Sarees'), ('kurti', 'Kurtis'), ('womenpants', 'Womenpants'), ('womentshirts', 'Womentshirts'), ('western', 'Western'), ('sweatshirts', 'Sweatshirts'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
