# Generated by Django 5.2.11 on 2026-04-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashion', '0009_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
